### ISSUE TITLE
Transfer ownership from dmjio to haskell-servant

### ISSUE THREAD

**Issue by dmjio** [haskell-servant/servant-swagger#14]
@jkarni, @fizruk. 

I'm going to be jammed this week (and potentially for the next few weeks). In an effort not to block progress on this repo @fizruk has proposed we transfer ownership to haskell-servant. I'm fine with this if you guys are.

All in favor say I

**Comment by fizruk** [comment]
:+1:

**Comment by dmjio** [comment]
@fizruk, @jkarni I don't have admin rights to `haskell-servant` so I can't transfer it. I've added @jkari as a maintainer here, so he can perform the transfer. Alternatively, @fizruk, if you have ownership rights, you can perform the transfer as well.

**Comment by fizruk** [comment]
Unfortunately, only the owner can transfer repo.

**Comment by fizruk** [comment]
(Collaborators can't access the Settings tab at all).

**Comment by dmjio** [comment]
help us @jkarni you're our only hope (star wars reference).

**Comment by dmjio** [comment]
@fizruk you are owner of this repo though right?

**Comment by fizruk** [comment]
No, you're the only owner, others are collaborators.

**Comment by fizruk** [comment]
You can actually see that in the top right corner of the comment box :)

**Comment by dmjio** [comment]
oh =)

**Comment by dmjio** [comment]
@fizruk, oh hmmm... so I can't promote you to owner?

**Comment by fizruk** [comment]
@dmjio no, you can only "promote" me to owner by transferring the repo ownership to me.

I think you should transfer the repo to @jkarni so that he would transfer it to @haskell-servant.

Maybe @jkarni should delete his fork before @dmjio tries transferring though.

**Comment by dmjio** [comment]
@soenkehahn, do you have admin rights to @haskell-servant :)

**Comment by jkarni** [comment]
I can't without forking since it seems I don't have enough rights to this. @dmjio you should be able to create a new repo in haskell-servant now.

OTOH, we maybe shouldalso consider merging with the main servant repo. (The advantage is that it is much easier to maintain, as any changes that would break -swagger will fail under CI.)

**Comment by dmjio** [comment]
@jkarni thanks, @fizruk the deed is done. 

> OTOH, we maybe should also consider merging with the main servant repo. (The advantage is that it is much easier to maintain, as any changes that would break -swagger will fail under CI.)

@fizruk, @jkarni I'm impartial on this issue, but I think @fizruk might have an opinion.

**Comment by fizruk** [comment]
> OTOH, we maybe shouldalso consider merging with the main servant repo. (The advantage is that it is much easier to maintain, as any changes that would break -swagger will fail under CI.)

Honestly, I don't think this is a good idea. I believe `servant` repo should only contain the **core** packages rather than the whole ecosystem. While I agree that Travis build for megarepo helps catch breakages across packages, I think having too many packages in a megarepo slows down the release process.

IIUC packages in `servant` megarepo get released in sync.
This makes it hard for useful changes to be released sooner.
E.g. haskell-servant/servant#228 was a breaking change for `servant-docs`, but not for other packages.
Another example is `servant-foreign` package which hasn't seen any release at all (see haskell-servant/servant#232). On the other hand `servant-foreign` is arguably a core package after all.

I don't find `servant-swagger` to be a core package and thus I don't think it belongs to the `servant` megarepo. I want to be able to release important changes as they come in.

**Comment by soenkehahn** [comment]
@fizruk: +1

**Comment by jkarni** [comment]
Agreed.
