### ISSUE TITLE
How to tweak `Capture` parameters with lenses?

### ISSUE THREAD

**Issue by soenkehahn** [haskell-servant/servant-swagger#27]
I'm trying to tweak the parameter description of a `Capture` parameter with lenses. In the `Swagger` it appears to be inlined in the `Operation` (using `Inline`) so I can't use the `parameters` lens.

- Is there a way to make `servant-swagger` *not* inline the parameters?
- Alternatively, is there a lens to modify all parameters with the same name, including the inlined ones?

As I'm new to both `lens` and `swagger2` I hope this all makes sense.

**Comment by fizruk** [comment]
### Is there a way to make `servant-swagger` _not_ inline the parameters?

Not currently.

Inlining happens in the `HasSwagger` instance for `Capture sym a :> api`.
You can provide a local overriding instance like this:

```haskell
instance {-# OVERLAPPING #-} HasSwagger api
  => HasSwagger (Capture "name" MyType :> api) where
  ...
```

But I think that won't be nice.

The problem with not inlining parameters by default is that they need to be named and I am not sure where to get that name from (since it should reflect both capture name and data type name to avoid name collisions).

However, maybe `servant-swagger` should provide means to factor out parameters. E.g. something like

```haskell
-- | Move parameter into parameter definitions block
-- and replace all of its occurrences with references.
nameParam :: HasSwagger (param :> AnyAPI) =>
  ParamName -> proxy param -> Swagger -> Swagger
```

Another approach might be to modify the `toSwagger` method of `HasSwagger` class to accept a list of parameter names. Something like this:

```haskell
type ParamDefinitions = [(Symbol, *)]

class HasSwagger api where
  toSwagger :: Proxy api -> Proxy (defs :: ParamDefinitions) -> Swagger

-- example of application-specific parameter naming
type MyParamDefinitions :: ParamDefinitions =
  [ ("pet_id_capture", Capture "pet_id" PetId)
  , ("pet_status", QueryParam "status" PetStatus)
  ]
```

These approaches also work for `Header` definitions which Swagger also supports.

### Alternatively, is there a lens to modify all parameters with the same name, including the inlined ones?

Note that in general you don't want to modify all parameters with the same name, but rather with the same name, location and schema.

To focus on the parameters you first need to focus on the operations. [`Data.Swagger.Operation`](http://hackage.haskell.org/package/swagger2-2.0.1/docs/Data-Swagger-Operation.html) provides some useful helpers as does [`Servant.Swagger`](http://hackage.haskell.org/package/servant-swagger-1.0.3/docs/Servant-Swagger.html#v:subOperations).

Here's an example of a lens, focusing on every inlined capture parameter with the name `"pet_id"`:

```haskell
-- | Check that a parameter is a capture with certain name.
isCapture :: ParamName -> Param -> Bool
isCapture n p = p ^. name == n && p ^? schema._ParamOther.in_ == Just ParamPath

-- | Focus on every capture of the operation with given name (regardless of its type).
captures :: ParamName -> Traversal' Operation Param
captures n = parameters.traverse._Inline.filtered (isCapture n)

-- set description for all inlined "pet_id" captures for all operations in a Swagger spec
allOperations.captures "pet_id".description ?~ "Just an ID for a pet."
```

A more dynamic approach is also available:

```haskell
import Data.Data.Lens

-- set description for all "pet_id" captures in the entire Swagger spec
-- note that this also includes parameter definitions
template.filtered (isCapture "pet_id").description ?~ "Just an ID for a pet"
```

I know that `lens` is heavy and `Swagger` is a pretty huge type, so these questions are totally okay!

We have decided to use `lens` precisely because the data model is huge and we cannot possibly cover all possible use cases a priori. Your use case is just one example of something I didn't think of before.
`lens` allows you to easily obtain a solution for this problem as demonstrated above (assuming you're familiar with `lens` and know where to look).

BTW, maybe `servant-swagger` should also provide helpers, allowing you to focus on inlined parameters, e.g.:

```haskell
-- | Focus on all operation parameters of given type.
params :: HasSwagger (param :> AnyAPI) => proxy param -> Traversal' Operation Param

-- set description for all "pet_id" captures for all operations in a Swagger spec
allOperations.params (Proxy :: Proxy (Capture "pet_id" PetId))
  .description ?~ "Just an ID for a pet"
```

**Comment by soenkehahn** [comment]
Thanks for the very informative answer. I need some time to digest this, but it really helps a lot. (Closing this issue.)

I can't find `_Inline` anywhere. Am I supposed to write that myself?

**Comment by fizruk** [comment]
@soenkehahn `_Inline` and many other prisms/lenses are defined in [`Data.Swagger.Lens`](http://hackage.haskell.org/package/swagger2-2.0.1/docs/Data-Swagger-Lens.html#v:_Inline) and are re-exported in `Data.Swagger`. You need `swagger2 >= 2.0`.

**Comment by soenkehahn** [comment]
Ah, I see. Thanks.
