### ISSUE TITLE
Tag new version?

### ISSUE THREAD

**Issue by JoshuaGross** [haskell-servant/servant-swagger#35]
Even without BasicAuth support, I think it would be useful to tag the latest release.

**Comment by fizruk** [comment]
FYI: I'll make a release after merging #31 (and #38).

**Comment by JoshuaGross** [comment]
Poke! Looks like that happened.

Sorry for bugging you again, just thought a reminder could help. Thanks for your work!

**Comment by fizruk** [comment]
@JoshuaGross Apologies for such long response times, I have been overloaded for the past few weeks!

I haven't released a new version since I realised that it would break compatibility with servant-0.4 (which many still use I think). I have restored support in #41. I'll try to merge it and release tonight!

**Comment by phadej** [comment]
AFAICS this is done

**Comment by fizruk** [comment]
@phadej yes, thanks for all the help!
