### ISSUE TITLE
microlens instead of lens for lighter installation ?

### ISSUE THREAD

**Issue by simonmichael** [haskell-servant/servant-swagger#39]
I inquired on IRC recently about replacing lens (in servant-swagger and swagger2) with microlens. microlens is a near drop-in replacement that builds much more quickly, which would provide a better experience and impression for everyone installing things depending on these libs (such as [hledger-api](http://hledger.org/hledger-api.html)). 

Since then @neongreen has released a new version of microlens (adding ~?) & microlens-th (adding makeClassy). Perhaps this makes it more viable ?

**Comment by neongreen** [comment]
(Not viable for swagger2, since it uses `makePrisms` which microlens can't provide due to the profunctors dependency.)

**Comment by phadej** [comment]
`lens` is very light dependency taken into account what `swagger2` requires anyway. If one removes `lens` and `insert-ordered-containers` from `swagger2` deps, there are:
```
StateVar 1.1.0.4
adjunctions 4.3
base-orphans 0.5.4
bifunctors 5.3
comonad 5
contravariant 1.4
distributive 0.5.0.2
exceptions 0.8.2.1
filepath 1.4.1.0
kan-extensions 5.0.1
lens 4.14
parallel 3.2.1.0
prelude-extras 0.4.0.3
profunctors 5.2
reflection 2.1.2
semigroupoids 5.0.1
semigroups 0.18.1
stm 2.4.4.1
transformers-compat 0.5.1.4
void 0.7.1
```

`base-orphans, exceptions, filepath, parallel, semigroups, stm, transformers-compat,` and `void` are more or less dependencies of anything real anyway. Rest is ekmett's *abstract non-sense*, but it's very very very hard to avoid it entirely nowadays.

I'm not sure what @fizruk's opinion on this is, but IMO it's not worth the effort.

**Comment by fizruk** [comment]
I personally have no problems with all those packages, especially since Stack makes it easy to build `lens` just once in a very long time (until you switch to a new snapshot). I also think that `lens` is essential for `swagger2` since it makes it very simple to manipulate Swagger specification.

However, if there's a strong need in a more lightweight dependency, we might separate the lens part of `swagger2` into a separate package, say, `swagger2-lens` and you can then provide a more lightweight `swagger2-microlens` or something. It would be harder to maintain these separate packages, and since I don't notice much want for it, I'd say it's not worth the effort (at least right now).
