### ISSUE TITLE
Handling of duplicate model names

### ISSUE THREAD

**Issue by gbaz** [haskell-servant/servant-swagger#77]
Say I have a module `A` that defines `Foo` which is given some `ToSchema` instance. And I have a module `B` that defines a different `Foo`. And now it happens my complete API has methods that use both types named `Foo`. In the current setup, it is possible that the Swagger generated will use the wrong `Foo` definition for a given method.

Is there a way to avoid this, or is this something that servant-swagger could be extended to be smarter about?

**Comment by fizruk** [comment]
@gbaz right, this isn't actually an issue with `servant-swagger`, but rather with `ToSchema` instances which are defined in `swagger2`.

See https://github.com/GetShopTV/swagger2/issues/14 for some discussion and possible solutions.

Basically, the solution would be to derive schemas with different names, for instance:

```haskell
instance ToSchema A.Foo where
  declareNamedSchema proxy = genericDeclareNamedSchema defaultSchemaOptions proxy
    & mapped.name ?~ "A.Foo"

instance ToSchema B.Foo where
  declareNamedSchema proxy = genericDeclareNamedSchema defaultSchemaOptions proxy
    & mapped.name ?~ "B.Foo"
```

I am closing this issue and encourage you to proceed with discussion in https://github.com/GetShopTV/swagger2/issues/14. Feel free to reopen if you feel this should be actually fixed in `servant-swagger`.
